### ISSUE TITLE
Camera box component is hiding the view of the interview screen

### ISSUE THREAD

**Issue by khanhdo05** [JoseG777/Ai-Tech-Interviewer-FE#4]
### Problem

The captured live camera box on the left side of the screen is blocking 1/3 of the interview screen behind and I can't read the questions. Consider making the component resizable, extendable, contractable, or movable across the screen.

### Recreate

- Go to here: [Interview]( https://ai-technical-interviewer.web.app/main )
- Choose coding language and time
- Click `Start Interview`

### Screenshot

![Screenshot 2024-07-28 160823](https://github.com/user-attachments/assets/17f4b7ae-d367-4468-b76e-bdb7b5b33dad)

### Comment

Great project! Congrats on winning!

**Comment by JoseG777** [comment]
Thanks for pointing this out! We appreciate your feedback and will look into this right now

**Comment by JoseG777** [comment]
Camera box is now resizable and moveable
